name: Main
on:
  push:
    branches:
      - main

jobs:
  master:
    strategy:
      matrix:
        node-version: [ 14.x ]
        step: ['build:release']
    name: ${{ matrix.step }}
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_USER_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: ${{ matrix.step }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          GH_PAT: ${{ secrets.GIT_USER_TOKEN }}
          GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install | grep -v 'YN0013'
          yarn ${{ matrix.step }}

  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: |
          echo "Dummy skip step"
